# 使用矩阵的笔记



首先要引入tensorflow并创建会话

In [1]:
import tensorflow as tf
from tensorflow.python.framework import ops
ops.reset_default_graph()

In [2]:
sess = tf.Session()
print(sess)

## 创建矩阵

diag方法可以从一个一维数组创建对角矩阵

In [4]:
diag_matrix = tf.diag([1.0,1.0,1.0])
# 此时打印的仅仅是这个矩阵的定义，不包含值，要run才有值
print(diag_matrix)
# 这里才打印出对角矩阵
print(sess.run(diag_matrix))

Tensor("Diag_1:0", shape=(3, 3), dtype=float32)
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


创建矩阵的几种方法：除了从diag创建对角矩阵，还有很多tf的创建张量的方法可以创建二维矩阵

In [30]:
# 正态分布
A = tf.truncated_normal([2,3])
print(sess.run(A))

# 填充
B = tf.fill([2,3],5.0)
print(sess.run(B))

# 随机
C = tf.random_uniform([3,2])
print(sess.run(C))

# 从numpy的u数组导入
import numpy as np

D = tf.convert_to_tensor(np.array([[1.,2.,3.],[-3.,-7.,-1.],[0.,5.,-2.]]))
print(sess.run(D))

[[ 1.1523463   0.070458    0.5607026 ]
 [-0.03997219 -1.5432627  -0.67451173]]
[[5. 5. 5.]
 [5. 5. 5.]]
[[0.3675202  0.11370814]
 [0.29109323 0.48812413]
 [0.58528507 0.6970837 ]]
[[ 1.  2.  3.]
 [-3. -7. -1.]
 [ 0.  5. -2.]]


## 矩阵的计算

In [17]:
print(sess.run(A+B))

print(sess.run(B-B))

[[3.9820123 4.4009657 5.4429116]
 [5.5559883 3.8690114 4.018817 ]]
[[0. 0. 0.]
 [0. 0. 0.]]


In [19]:
# 矩阵叉乘
diag_matrix = tf.diag([2.0,2.0,2.0])
print(sess.run(tf.matmul(B,diag_matrix)))

[[10. 10. 10.]
 [10. 10. 10.]]


In [22]:
# 矩阵转置 矩阵沿左上到右下的对角线镜面翻转
print(sess.run(D))
print(sess.run(tf.transpose(D)))

[[ 1.  2.  3.]
 [-1. -7. -3.]
 [ 0.  5. -2.]]
[[ 1. -1.  0.]
 [ 2. -7.  5.]
 [ 3. -3. -2.]]


In [25]:
# 矩阵行列式 有精度问题
print(sess.run(tf.matrix_determinant(D)))


9.999999999999998


In [31]:
# 逆矩阵
print(sess.run(D))
print(sess.run(tf.matrix_inverse(D)))
print(sess.run(tf.matmul(D,tf.matrix_inverse(D))))
# 矩阵叉乘逆矩阵应该为单位矩阵（对角线为1,其余为0），但是由于精度问题会有错误出现

[[ 1.  2.  3.]
 [-3. -7. -1.]
 [ 0.  5. -2.]]
[[-0.5        -0.5        -0.5       ]
 [ 0.15789474  0.05263158  0.21052632]
 [ 0.39473684  0.13157895  0.02631579]]
[[ 1.00000000e+00  0.00000000e+00 -8.32667268e-17]
 [-1.11022302e-16  1.00000000e+00  1.04083409e-16]
 [ 1.11022302e-16  0.00000000e+00  1.00000000e+00]]


In [33]:
# 矩阵分解 cholesky分解法
print(sess.run(diag_matrix))
print(sess.run(tf.cholesky(diag_matrix)))


[[2. 0. 0.]
 [0. 2. 0.]
 [0. 0. 2.]]
[[1.4142135 0.        0.       ]
 [0.        1.4142135 0.       ]
 [0.        0.        1.4142135]]


In [ ]:
# 矩阵特征值，特征向量
print(sess.run(tf.self_adjoint_eig(D)))